spring:
  datasource:
    url: jdbc:h2:mem:recipedb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    defer-datasource-initialization: true
logging:
  level:
    com.springosyrs.spring5recipea: debug

